const Mazda = [
        {
          "brand": "MAZDA",
          "model": "121 METRO/DEMIO/FESTIVA",
          "series": "DW3/5W",
          "dateRange": "98/01~02/12",
          "ikoma": "FR",
          "": "",
          "kyb": 333266,
          "__1": "PCL-640",
          "__2": 333267
        },
        {
          "brand": "MAZDA",
          "model": "121 METRO/DEMIO/FESTIVA",
          "series": "DW3/5W",
          "dateRange": "98/01~99/12",
          "ikoma": "RR",
          "": "",
          "kyb": 341252,
          "__1": "PCL-639",
          "__2": ""
        },
        {
          "brand": "MAZDA",
          "model": "121 METRO/DEMIO/FESTIVA",
          "series": "DW3/5W",
          "dateRange": "00/01~02/12",
          "ikoma": "RR",
          "": "",
          "kyb": 341323,
          "__1": "PCL-641",
          "__2": ""
        },
        {
          "brand": "MAZDA",
          "model": "323/FAMILIA/LASER",
          "series": "BF;BG",
          "dateRange": "89/01~94/08",
          "ikoma": "FR",
          "": "",
          "kyb": 333126,
          "__1": "PCL-110",
          "__2": 333127
        },
        {
          "brand": "MAZDA",
          "model": "323/FAMILIA/LASER",
          "series": "BF;BG",
          "dateRange": "89/01~94/08",
          "ikoma": "RR",
          "": "",
          "kyb": 333132,
          "__1": "PCL-111",
          "__2": 333133
        },
        {
          "brand": "MAZDA",
          "model": "323/FAMILIA/LIATA/FORD\n  LASER",
          "series": "BHA",
          "dateRange": "94/09~",
          "ikoma": "FR",
          "": "",
          "kyb": 333178,
          "__1": "PCL-074",
          "__2": 333179
        },
        {
          "brand": "MAZDA",
          "model": "323/FAMILIA/LIATA/FORD\n  LASER",
          "series": "BHA",
          "dateRange": "94/09~",
          "ikoma": "RR",
          "": "",
          "kyb": 333180,
          "__1": "PCL-075",
          "__2": 333181
        },
        {
          "brand": "MAZDA",
          "model": "323/FAMILIA/LIATA/FORD\n  LASER",
          "series": "BHA",
          "dateRange": "96~",
          "ikoma": "FR",
          "": "",
          "kyb": 333292,
          "__1": "PCL-636",
          "__2": 333293
        },
        {
          "brand": "MAZDA",
          "model": "323/FAMILIA/LIATA/FORD\n  LASER",
          "series": "BHA",
          "dateRange": "96~",
          "ikoma": "RR",
          "": "",
          "kyb": 333294,
          "__1": "PCL-637",
          "__2": 333295
        },
        {
          "brand": "MAZDA",
          "model": "BJE/3/5P (2WD)",
          "series": "FR",
          "dateRange": "98~00",
          "ikoma": "PCL-066",
          "": 333274,
          "kyb": 333275,
          "__1": "",
          "__2": ""
        },
        {
          "brand": "MAZDA",
          "model": "BJ (2WD)",
          "series": "FR",
          "dateRange": "00~03",
          "ikoma": "PCL-068",
          "": 333350,
          "kyb": 333351,
          "__1": "",
          "__2": ""
        },
        {
          "brand": "MAZDA",
          "model": "BJE/3/5P;BJ (2WD)",
          "series": "RR",
          "dateRange": "98~03",
          "ikoma": "PCL-067",
          "": 333276,
          "kyb": 333277,
          "__1": "",
          "__2": ""
        },
        {
          "brand": "MAZDA",
          "model": "BJ (2WD) Heightening\n  Clearance",
          "series": "RR",
          "dateRange": "98~03",
          "ikoma": "PCL-065",
          "": 333296,
          "kyb": 333297,
          "__1": "",
          "__2": ""
        },
        {
          "brand": "MAZDA",
          "model": "BJ8W (4WD)**",
          "series": "RR",
          "dateRange": "98~03",
          "ikoma": "PCL-675",
          "": "",
          "kyb": "",
          "__1": "",
          "__2": ""
        },
        {
          "brand": "MAZDA",
          "model": "626/MX6/FORD TELSTAR",
          "series": "GE 12/14",
          "dateRange": "93~97/05",
          "ikoma": "FR",
          "": "",
          "kyb": 334082,
          "__1": "PCL-072",
          "__2": 334083
        },
        {
          "brand": "MAZDA",
          "model": "626/MX6/FORD TELSTAR",
          "series": "GE 12/14",
          "dateRange": "93~97/05",
          "ikoma": "RR",
          "": "",
          "kyb": 334157,
          "__1": "PCL-073",
          "__2": ""
        },
        {
          "brand": "MAZDA",
          "model": "BONGO FRIENDEE",
          "series": "SG##",
          "dateRange": "95/05~",
          "ikoma": "FR",
          "": "",
          "kyb": 334434,
          "__1": "PCL-678",
          "__2": 334435
        },
        {
          "brand": "MAZDA",
          "model": "BONGO FRIENDEE",
          "series": "SG##",
          "dateRange": "95/05~",
          "ikoma": "RR",
          "": "PCI-211",
          "kyb": 345048,
          "__1": "",
          "__2": ""
        },
        {
          "brand": "MAZDA",
          "model": "CX-5",
          "series": "ALL",
          "dateRange": "13~",
          "ikoma": "FR",
          "": "",
          "kyb": 339336,
          "__1": "Inquiry",
          "__2": 339337
        },
        {
          "brand": "MAZDA",
          "model": "CX-5",
          "series": "ALL",
          "dateRange": "13~",
          "ikoma": "RR",
          "": "Inquiry",
          "kyb": 349219,
          "__1": "",
          "__2": ""
        },
        {
          "brand": "MAZDA",
          "model": "CX-7",
          "series": "ALL",
          "dateRange": "07~",
          "ikoma": "FR",
          "": "",
          "kyb": 339155,
          "__1": "Inquiry",
          "__2": 339156
        },
        {
          "brand": "MAZDA",
          "model": "CX-7",
          "series": "ALL",
          "dateRange": "07~",
          "ikoma": "RR",
          "": "Inquiry",
          "kyb": 349076,
          "__1": "",
          "__2": ""
        },
        {
          "brand": "MAZDA",
          "model": "CX-9",
          "series": "ALL",
          "dateRange": "07~",
          "ikoma": "FR",
          "": "",
          "kyb": 339140,
          "__1": "Inquiry",
          "__2": 339141
        },
        {
          "brand": "MAZDA",
          "model": "CX-9",
          "series": "ALL",
          "dateRange": "07~",
          "ikoma": "RR",
          "": "Inquiry",
          "kyb": 349070,
          "__1": "",
          "__2": ""
        },
        {
          "brand": "MAZDA",
          "model": "DEMIO / MAZDA 2 / FIESTA",
          "series": "DY/JH",
          "dateRange": "07~",
          "ikoma": "FR",
          "": "",
          "kyb": 333494,
          "__1": "Inquiry",
          "__2": 333495
        },
        {
          "brand": "MAZDA",
          "model": "DEMIO / MAZDA 2 / FIESTA",
          "series": "DY/JH",
          "dateRange": "07~",
          "ikoma": "FR",
          "": "Inquiry",
          "kyb": 348018,
          "__1": "",
          "__2": ""
        },
        {
          "brand": "MAZDA",
          "model": "DEMIO / VERISA",
          "series": "DY;DC",
          "dateRange": "03~07",
          "ikoma": "FR",
          "": "",
          "kyb": 333414,
          "__1": "PCL-102",
          "__2": 333415
        },
        {
          "brand": "MAZDA",
          "model": "DEMIO / VERISA",
          "series": "DY;DC",
          "dateRange": "03~07",
          "ikoma": "FR",
          "": "PCI-103",
          "kyb": 553308,
          "__1": "",
          "__2": ""
        },
        {
          "brand": "MAZDA",
          "model": "MAZDA 3 / AXELA",
          "series": "1.4/1.6/2.0",
          "dateRange": "03/11~",
          "ikoma": "FR",
          "": "",
          "kyb": 334700,
          "__1": "PCL-676",
          "__2": 334701
        },
        {
          "brand": "MAZDA",
          "model": "MAZDA 3 / AXELA",
          "series": "1.4/1.6/2.0",
          "dateRange": "03/11~",
          "ikoma": "RR",
          "": "PCI-192",
          "kyb": 343412,
          "__1": "PCL-677",
          "__2": ""
        },
        {
          "brand": "MAZDA",
          "model": "MAZDA 5 / PREMACY",
          "series": "ALL",
          "dateRange": "05~",
          "ikoma": "FR",
          "": "",
          "kyb": 339820,
          "__1": "PCL-680",
          "__2": 339821
        },
        {
          "brand": "MAZDA",
          "model": "MAZDA 5 / PREMACY",
          "series": "ALL",
          "dateRange": "05~",
          "ikoma": "RR",
          "": "PCI-221",
          "kyb": 343412,
          "__1": "",
          "__2": ""
        },
        {
          "brand": "MAZDA",
          "model": "MAZDA 6 / ATENZA",
          "series": "GG3S/GY3W",
          "dateRange": "02/05~",
          "ikoma": "FR",
          "": "",
          "kyb": 341351,
          "__1": "PCL-630",
          "__2": 341352
        },
        {
          "brand": "MAZDA",
          "model": "MAZDA 6 / ATENZA",
          "series": "GG3S/GY3W",
          "dateRange": "02/05~",
          "ikoma": "FR",
          "": "",
          "kyb": 341314,
          "__1": "PCL-630",
          "__2": 341315
        },
        {
          "brand": "MAZDA",
          "model": "MAZDA 6 / ATENZA",
          "series": "GG3S/GY3W",
          "dateRange": "02/05~",
          "ikoma": "RR",
          "": "PCI-189",
          "kyb": 344363,
          "__1": "PCL-631",
          "__2": ""
        },
        {
          "brand": "MAZDA",
          "model": "MPV",
          "series": "LVEW",
          "dateRange": "89/11~99/08",
          "ikoma": "FR",
          "": "",
          "kyb": 335009,
          "__1": "PCL-600",
          "__2": 335010
        },
        {
          "brand": "MAZDA",
          "model": "MPV",
          "series": "LVEW",
          "dateRange": "89/11~99/08",
          "ikoma": "RR",
          "": "PCI-142",
          "kyb": 345033,
          "__1": "",
          "__2": ""
        },
        {
          "brand": "MAZDA",
          "model": "MPV",
          "series": "LW5W",
          "dateRange": "99~06",
          "ikoma": "FR",
          "": "",
          "kyb": 334282,
          "__1": "Inquiry",
          "__2": 334283
        },
        {
          "brand": "MAZDA",
          "model": "MPV",
          "series": "LW5W",
          "dateRange": "99~06",
          "ikoma": "RR",
          "": "PCI-214",
          "kyb": 345024,
          "__1": "",
          "__2": ""
        },
        {
          "brand": "MAZDA",
          "model": "PREMACY",
          "series": "CP#",
          "dateRange": "01/07~",
          "ikoma": "FR",
          "": "",
          "kyb": 333350,
          "__1": "PCL-068",
          "__2": 333351
        },
        {
          "brand": "MAZDA",
          "model": "PREMACY",
          "series": "CP#",
          "dateRange": "99/07~",
          "ikoma": "RR",
          "": "",
          "kyb": 334259,
          "__1": "PCL-069",
          "__2": 334260
        },
        {
          "brand": "MAZDA",
          "model": "TRIBUTE/FORD ESCAPE",
          "series": "Y11;EPEW;EPFW 2WD",
          "dateRange": "01/03~",
          "ikoma": "FR",
          "": "",
          "kyb": 334333,
          "__1": "PCL-062",
          "__2": 334334
        },
        {
          "brand": "MAZDA",
          "model": "TRIBUTE/FORD ESCAPE",
          "series": "Y11;EPEW;EPFW 4WD",
          "dateRange": "04/01~",
          "ikoma": "FR",
          "": "",
          "kyb": 339068,
          "__1": "PCL-064",
          "__2": 339069
        },
        {
          "brand": "MAZDA",
          "model": "TRIBUTE/FORD ESCAPE",
          "series": "Y11;EPEW;EPFW 4WD",
          "dateRange": "01/03~",
          "ikoma": "RR",
          "": "",
          "kyb": 344356,
          "__1": "PCL-063",
          "__2": ""
        }
];

export default Mazda;