const Nissan = [
        {
          "brand": "NISSAN",
          "model": "AD WAGON",
          "series": "Y10",
          "dateRange": "96~99",
          "ikoma": "FR",
          "": "",
          "kyb": 333089,
          "__1": "PCL-114",
          "__2": 333090
        },
        {
          "brand": "NISSAN",
          "model": "AD WAGON",
          "series": "Y10",
          "dateRange": "96~99",
          "ikoma": "RR",
          "": "PCI-198",
          "kyb": 343240,
          "__1": "",
          "__2": ""
        },
        {
          "brand": "NISSAN",
          "model": "AD WAGON",
          "series": "Y11",
          "dateRange": "99~05",
          "ikoma": "FR",
          "": "",
          "kyb": 333310,
          "__1": "PCL-058",
          "__2": 333311
        },
        {
          "brand": "NISSAN",
          "model": "AD WAGON",
          "series": "Y11(*56211-WD301/326)",
          "dateRange": "99~05",
          "ikoma": "RR",
          "": "PCL-025",
          "kyb": 340101,
          "__1": "PCL-123*",
          "__2": 340102
        },
        {
          "brand": "NISSAN",
          "model": "ARMADA",
          "series": "WA60",
          "dateRange": "03~15",
          "ikoma": "FR",
          "": "",
          "kyb": 341600,
          "__1": "PCL-002*",
          "__2": ""
        },
        {
          "brand": "NISSAN",
          "model": "ARMADA",
          "series": "WA60",
          "dateRange": "03~15",
          "ikoma": "RR",
          "": "Inquiry",
          "kyb": 345066,
          "__1": "",
          "__2": ""
        },
        {
          "brand": "NISSAN",
          "model": "ALTIMA",
          "series": "L31",
          "dateRange": "01~06",
          "ikoma": "FR",
          "": "",
          "kyb": 334336,
          "__1": "PCL-400",
          "__2": 334337
        },
        {
          "brand": "NISSAN",
          "model": "ALTIMA",
          "series": "L31",
          "dateRange": "01~06",
          "ikoma": "RR",
          "": "",
          "kyb": 344395,
          "__1": "PCL-401",
          "__2": ""
        },
        {
          "brand": "NISSAN",
          "model": "ALTIMA",
          "series": "L32",
          "dateRange": "06~12",
          "ikoma": "FR",
          "": "",
          "kyb": 339146,
          "__1": "PCL-406",
          "__2": 339147
        },
        {
          "brand": "NISSAN",
          "model": "ALTIMA",
          "series": "L32",
          "dateRange": "06~12",
          "ikoma": "RR",
          "": "",
          "kyb": 349075,
          "__1": "PCL-407",
          "__2": ""
        },
        {
          "brand": "NISSAN",
          "model": "ALTIMA",
          "series": "L33",
          "dateRange": "13~",
          "ikoma": "FR",
          "": "",
          "kyb": 339331,
          "__1": "Inquiry",
          "__2": 339332
        },
        {
          "brand": "NISSAN",
          "model": "ALTIMA",
          "series": "L33",
          "dateRange": "13~",
          "ikoma": "RR",
          "": "",
          "kyb": 349075,
          "__1": "PCL-407",
          "__2": ""
        },
        {
          "brand": "NISSAN",
          "model": "BLUEBIRD/ALTIMA",
          "series": "HU13/PU13",
          "dateRange": "91/09~95/08",
          "ikoma": "FR",
          "": "",
          "kyb": 334222,
          "__1": "PCL-430",
          "__2": 334223
        },
        {
          "brand": "NISSAN",
          "model": "BLUEBIRD/ALTIMA",
          "series": "HU13/PU13",
          "dateRange": "91/09~95/08",
          "ikoma": "RR",
          "": "",
          "kyb": 334135,
          "__1": "PCL-431",
          "__2": 334136
        },
        {
          "brand": "NISSAN",
          "model": "BLUEBIRD SYLPHY",
          "series": "G11",
          "dateRange": "06~",
          "ikoma": "FR",
          "": "",
          "kyb": 333472,
          "__1": "PCL-470",
          "__2": 333473
        },
        {
          "brand": "NISSAN",
          "model": "BLUEBIRD SYLPHY",
          "series": "G11",
          "dateRange": "06~",
          "ikoma": "RR",
          "": "PCI-174",
          "kyb": 343465,
          "__1": "PCL-483",
          "__2": ""
        },
        {
          "brand": "NISSAN",
          "model": "BLUEBIRD SYLPHY",
          "series": "B17",
          "dateRange": "12~",
          "ikoma": "FR",
          "": "",
          "kyb": 339367,
          "__1": "Inquiry",
          "__2": 339368
        },
        {
          "brand": "NISSAN",
          "model": "BLUEBIRD SYLPHY",
          "series": "B17",
          "dateRange": "12~",
          "ikoma": "RR",
          "": "",
          "kyb": 349240,
          "__1": "Inquiry",
          "__2": ""
        },
        {
          "brand": "NISSAN",
          "model": "FRONTIER",
          "series": "D40",
          "dateRange": "04~15",
          "ikoma": "FR",
          "": "Inquiry",
          "kyb": 341467,
          "__1": "",
          "__2": ""
        },
        {
          "brand": "NISSAN",
          "model": "FRONTIER",
          "series": "D40",
          "dateRange": "04~15",
          "ikoma": "RR",
          "": "Inquiry",
          "kyb": 345067,
          "__1": "",
          "__2": ""
        },
        {
          "brand": "NISSAN",
          "model": "LARGO",
          "series": "NW30 4WD",
          "dateRange": "93-97",
          "ikoma": "FR",
          "": "",
          "kyb": 333352,
          "__1": "Inquiry",
          "__2": 333353
        },
        {
          "brand": "NISSAN",
          "model": "LARGO",
          "series": "NW30 4WD",
          "dateRange": "93-97",
          "ikoma": "RR",
          "": "PCI-210",
          "kyb": 344390,
          "__1": "",
          "__2": ""
        },
        {
          "brand": "NISSAN",
          "model": "MICRA/MARCH",
          "series": "K11",
          "dateRange": "92~02",
          "ikoma": "FR",
          "": "",
          "kyb": 332061,
          "__1": "PCL-018",
          "__2": 332062
        },
        {
          "brand": "NISSAN",
          "model": "MICRA/MARCH",
          "series": "K11",
          "dateRange": "92~02",
          "ikoma": "RR",
          "": "",
          "kyb": 343249,
          "__1": "PCL-019",
          "__2": ""
        },
        {
          "brand": "NISSAN",
          "model": "MICRA/MARCH",
          "series": "K12",
          "dateRange": "02/02~",
          "ikoma": "FR",
          "": "",
          "kyb": 333396,
          "__1": "Inquiry",
          "__2": 333397
        },
        {
          "brand": "NISSAN",
          "model": "MICRA/MARCH",
          "series": "K12",
          "dateRange": "02/02~",
          "ikoma": "RR",
          "": "PCI-199",
          "kyb": 343421,
          "__1": "PCL-221",
          "__2": ""
        },
        {
          "brand": "NISSAN",
          "model": "MICRA/MARCH",
          "series": "K13",
          "dateRange": "10~",
          "ikoma": "FR",
          "": "",
          "kyb": 332141,
          "__1": "Inquiry",
          "__2": 332142
        },
        {
          "brand": "NISSAN",
          "model": "MICRA/MARCH",
          "series": "K13",
          "dateRange": "10~",
          "ikoma": "RR",
          "": "",
          "kyb": 348029,
          "__1": "Inquiry",
          "__2": ""
        },
        {
          "brand": "NISSAN",
          "model": "MAXIMA/810/INFINITI\n  I30/CEFIRO",
          "series": "A32(334150/334151)",
          "dateRange": "94/08~98/12",
          "ikoma": "FR",
          "": "",
          "kyb": 334480,
          "__1": "PCL-022",
          "__2": 334481
        },
        {
          "brand": "NISSAN",
          "model": "MAXIMA/810/INFINITI\n  I30/CEFIRO",
          "series": "A32",
          "dateRange": "94/08~98/12",
          "ikoma": "RR",
          "": "",
          "kyb": 341202,
          "__1": "PCL-023",
          "__2": ""
        },
        {
          "brand": "NISSAN",
          "model": "MAXIMA/810/INFINITI\n  I30/CEFIRO",
          "series": "A33(334265/334266)",
          "dateRange": "98/12~02/08",
          "ikoma": "FR",
          "": "",
          "kyb": 334366,
          "__1": "PCL-112",
          "__2": 334367
        },
        {
          "brand": "NISSAN",
          "model": "MAXIMA/810/INFINITI\n  I30/CEFIRO",
          "series": "A33",
          "dateRange": "98/12~02/08",
          "ikoma": "RR",
          "": "",
          "kyb": 341341,
          "__1": "PCL-113",
          "__2": 341271
        },
        {
          "brand": "NISSAN",
          "model": "MAXIMA",
          "series": "L31",
          "dateRange": "01~06",
          "ikoma": "FR",
          "": "",
          "kyb": 334336,
          "__1": "PCL-400",
          "__2": 334337
        },
        {
          "brand": "NISSAN",
          "model": "MAXIMA",
          "series": "L31",
          "dateRange": "01~06",
          "ikoma": "RR",
          "": "",
          "kyb": 344395,
          "__1": "PCL-401",
          "__2": ""
        },
        {
          "brand": "NISSAN",
          "model": "MAXIMA",
          "series": "L32",
          "dateRange": "07~13",
          "ikoma": "FR",
          "": "",
          "kyb": 339190,
          "__1": "PCL-406*",
          "__2": 339191
        },
        {
          "brand": "NISSAN",
          "model": "MAXIMA",
          "series": "L32",
          "dateRange": "07~13",
          "ikoma": "RR",
          "": "",
          "kyb": 349075,
          "__1": "PCL-407*",
          "__2": 349139
        },
        {
          "brand": "NISSAN",
          "model": "MURANO",
          "series": "Z50",
          "dateRange": "02~07",
          "ikoma": "FR",
          "": "",
          "kyb": 334380,
          "__1": "PCL-492",
          "__2": 334381
        },
        {
          "brand": "NISSAN",
          "model": "MURANO",
          "series": "Z50",
          "dateRange": "02~07",
          "ikoma": "RR",
          "": "PCI-229",
          "kyb": 344439,
          "__1": "",
          "__2": ""
        },
        {
          "brand": "NISSAN",
          "model": "MURANO",
          "series": "Z51",
          "dateRange": "08~14",
          "ikoma": "FR",
          "": "",
          "kyb": 339188,
          "__1": "Inquiry",
          "__2": 339189
        },
        {
          "brand": "NISSAN",
          "model": "MURANO",
          "series": "Z51",
          "dateRange": "08~14",
          "ikoma": "RR",
          "": "Inquiry",
          "kyb": 349092,
          "__1": "",
          "__2": ""
        },
        {
          "brand": "NISSAN",
          "model": "NAVARA Pick-up",
          "series": "D21/D22 2WD",
          "dateRange": "97~",
          "ikoma": "FR",
          "": "PCI-079",
          "kyb": 343342,
          "__1": "",
          "__2": ""
        },
        {
          "brand": "NISSAN",
          "model": "NAVARA Pick-up",
          "series": "D21/D22 2WD",
          "dateRange": "97~",
          "ikoma": "RR",
          "": "PCI-080",
          "kyb": 343343,
          "__1": "",
          "__2": ""
        },
        {
          "brand": "NISSAN",
          "model": "NAVARA Pick-up",
          "series": "D21/D22 4WD",
          "dateRange": "97~",
          "ikoma": "FR",
          "": "PCI-236",
          "kyb": 344475,
          "__1": "",
          "__2": ""
        },
        {
          "brand": "NISSAN",
          "model": "NAVARA Pick-up",
          "series": "D21/D22 4WD",
          "dateRange": "97~",
          "ikoma": "RR",
          "": "PCI-235",
          "kyb": 344015,
          "__1": "",
          "__2": 344476
        },
        {
          "brand": "NISSAN",
          "model": "NAVARA Pick-up",
          "series": "D40",
          "dateRange": "04~15",
          "ikoma": "FR",
          "": "PCI-088",
          "kyb": 340053,
          "__1": "",
          "__2": ""
        },
        {
          "brand": "NISSAN",
          "model": "NAVARA Pick-up",
          "series": "D40",
          "dateRange": "04~15",
          "ikoma": "RR",
          "": "PCI-087",
          "kyb": 349111,
          "__1": "",
          "__2": ""
        },
        {
          "brand": "NISSAN",
          "model": "PATHFINDER",
          "series": "R51 EU",
          "dateRange": "05~",
          "ikoma": "FR",
          "": "",
          "kyb": 341461,
          "__1": "PCL-002",
          "__2": ""
        },
        {
          "brand": "NISSAN",
          "model": "PATHFINDER",
          "series": "R51",
          "dateRange": "05~",
          "ikoma": "FR",
          "": "",
          "kyb": 341468,
          "__1": "PCL-002*",
          "__2": ""
        },
        {
          "brand": "NISSAN",
          "model": "PATHFINDER",
          "series": "R51",
          "dateRange": "05~",
          "ikoma": "RR",
          "": "Inquiry",
          "kyb": 345056,
          "__1": "",
          "__2": ""
        },
        {
          "brand": "NISSAN",
          "model": "PATROL/SAFARI",
          "series": "Y60/Y61",
          "dateRange": "87/10~",
          "ikoma": "FR",
          "": "PCI-085",
          "kyb": 344360,
          "__1": "",
          "__2": ""
        },
        {
          "brand": "NISSAN",
          "model": "PATROL/SAFARI",
          "series": "Y60/Y61",
          "dateRange": "87/10~",
          "ikoma": "RR",
          "": "PCI-086",
          "kyb": 345007,
          "__1": "",
          "__2": ""
        },
        {
          "brand": "NISSAN",
          "model": "PATROL/SAFARI",
          "series": "Y61",
          "dateRange": "97~",
          "ikoma": "FR",
          "": "",
          "kyb": 344360,
          "__1": "PCL-026",
          "__2": ""
        },
        {
          "brand": "NISSAN",
          "model": "PATROL/SAFARI",
          "series": "Y61",
          "dateRange": "97~",
          "ikoma": "RR",
          "": "",
          "kyb": 344361,
          "__1": "PCL-027",
          "__2": ""
        },
        {
          "brand": "NISSAN",
          "model": "PRESAGE/BASSARA",
          "series": "U30 (54302-AD006)",
          "dateRange": "98~03",
          "ikoma": "FR",
          "": "",
          "kyb": "",
          "__1": "PCL-116",
          "__2": ""
        },
        {
          "brand": "NISSAN",
          "model": "PRESAGE/BASSARA",
          "series": "U30 2WD",
          "dateRange": "98~03",
          "ikoma": "RR",
          "": "PCI-196",
          "kyb": 343389,
          "__1": "",
          "__2": ""
        },
        {
          "brand": "NISSAN",
          "model": "PRESAGE/BASSARA",
          "series": "U30 4WD",
          "dateRange": "98~03",
          "ikoma": "RR",
          "": "PCI-205",
          "kyb": 343390,
          "__1": "",
          "__2": ""
        },
        {
          "brand": "NISSAN",
          "model": "PRIMERA/INFINITI G20",
          "series": "P10",
          "dateRange": "90~96",
          "ikoma": "FR",
          "": "",
          "kyb": 341120,
          "__1": "PCL-088",
          "__2": ""
        },
        {
          "brand": "NISSAN",
          "model": "PRIMERA/INFINITI G20",
          "series": "P10",
          "dateRange": "90~96",
          "ikoma": "RR",
          "": "",
          "kyb": 333103,
          "__1": "PCL-089",
          "__2": 333104
        },
        {
          "brand": "NISSAN",
          "model": "PRIMERA/BLUEBIRD/G20",
          "series": "P11/U14",
          "dateRange": "96~02",
          "ikoma": "FR",
          "": "",
          "kyb": 341120,
          "__1": "PCL-088",
          "__2": ""
        },
        {
          "brand": "NISSAN",
          "model": "PRIMERA/BLUEBIRD/G20",
          "series": "P11/U14",
          "dateRange": "96~02",
          "ikoma": "RR",
          "": "",
          "kyb": 341186,
          "__1": "PCL-037",
          "__2": ""
        },
        {
          "brand": "NISSAN",
          "model": "PRIMERA/BLUEBIRD/G20",
          "series": "P12",
          "dateRange": "01~08",
          "ikoma": "FR",
          "": "",
          "kyb": 331014,
          "__1": "*Inquiry*",
          "__2": 331015
        },
        {
          "brand": "NISSAN",
          "model": "PRIMERA/BLUEBIRD/G20",
          "series": "P12",
          "dateRange": "01~08",
          "ikoma": "RR",
          "": "",
          "kyb": 341325,
          "__1": "PCL-487",
          "__2": ""
        },
        {
          "brand": "NISSAN",
          "model": "",
          "series": "J10",
          "dateRange": "07~13",
          "ikoma": "FR",
          "": "",
          "kyb": 339196,
          "__1": "PCL-498",
          "__2": 339197
        },
        {
          "brand": "NISSAN",
          "model": "",
          "series": "J10",
          "dateRange": "07~13",
          "ikoma": "RR",
          "": "",
          "kyb": 349079,
          "__1": "PCL-199",
          "__2": ""
        },
        {
          "brand": "NISSAN",
          "model": "R'NESSA",
          "series": "N30 (54302-AD006)",
          "dateRange": "97~01",
          "ikoma": "FR",
          "": "",
          "kyb": "",
          "__1": "PCL-116",
          "__2": ""
        },
        {
          "brand": "NISSAN",
          "model": "R'NESSA",
          "series": "N30 2WD",
          "dateRange": "97~01",
          "ikoma": "RR",
          "": "PCI-196",
          "kyb": 343389,
          "__1": "",
          "__2": ""
        },
        {
          "brand": "NISSAN",
          "model": "R'NESSA",
          "series": "N30 4WD",
          "dateRange": "",
          "ikoma": "",
          "": "PCI-205",
          "kyb": 343390,
          "__1": "",
          "__2": ""
        },
        {
          "brand": "NISSAN",
          "model": "SUNNY/SENTRA/ALMERA",
          "series": "B12;N13",
          "dateRange": "86/06~90/09",
          "ikoma": "FR",
          "": "",
          "kyb": 332028,
          "__1": "PCL-402",
          "__2": 332029
        },
        {
          "brand": "NISSAN",
          "model": "SUNNY/SENTRA/ALMERA",
          "series": "B12;N13",
          "dateRange": "86/06~90/09",
          "ikoma": "RR",
          "": "",
          "kyb": 332026,
          "__1": "PCL-403",
          "__2": 332027
        },
        {
          "brand": "NISSAN",
          "model": "SUNNY/SENTRA/ALMERA",
          "series": "B13/N14 (2WD\n  1.3/1.4/1.5/1.7D)",
          "dateRange": "90/01~94/12",
          "ikoma": "FR",
          "": "",
          "kyb": 333089,
          "__1": "PCL-114",
          "__2": 333090
        },
        {
          "brand": "NISSAN",
          "model": "SUNNY/SENTRA/ALMERA",
          "series": "B13/N14 (2WD\n  1.3/1.4/1.5/1.7D)",
          "dateRange": "90/01~94/12",
          "ikoma": "RR",
          "": "",
          "kyb": 332056,
          "__1": "PCL-115",
          "__2": 332057
        },
        {
          "brand": "NISSAN",
          "model": "SUNNY/SENTRA/ALMERA",
          "series": "AB14/AN15(2WD)",
          "dateRange": "95/01~97/07",
          "ikoma": "FR",
          "": "",
          "kyb": 333192,
          "__1": "PCL-034",
          "__2": 333193
        },
        {
          "brand": "NISSAN",
          "model": "SUNNY/SENTRA/ALMERA",
          "series": "AB14/AN15/AR11",
          "dateRange": "97/8~00/02",
          "ikoma": "FR",
          "": "",
          "kyb": 333238,
          "__1": "PCL-418",
          "__2": 333239
        },
        {
          "brand": "NISSAN",
          "model": "SUNNY/SENTRA/ALMERA",
          "series": "AB14/AN15(2WD)",
          "dateRange": "95/01~97/07",
          "ikoma": "RR",
          "": "",
          "kyb": 341186,
          "__1": "PCL-037",
          "__2": ""
        },
        {
          "brand": "NISSAN",
          "model": "SUNNY/SENTRA/ALMERA",
          "series": "B15(2WD);N16",
          "dateRange": "98/10~",
          "ikoma": "FR",
          "": "",
          "kyb": 333308,
          "__1": "PCL-058",
          "__2": 333309
        },
        {
          "brand": "NISSAN",
          "model": "SUNNY/SENTRA/ALMERA",
          "series": "B15(2WD);N16",
          "dateRange": "98/10~",
          "ikoma": "RR",
          "": "",
          "kyb": 341279,
          "__1": "PCL-059",
          "__2": ""
        },
        {
          "brand": "NISSAN",
          "model": "SUNNY/SENTRA",
          "series": "N17",
          "dateRange": "11~",
          "ikoma": "FR",
          "": "",
          "kyb": 332152,
          "__1": "PCL-420",
          "__2": 332153
        },
        {
          "brand": "NISSAN",
          "model": "SUNNY/SENTRA",
          "series": "N17",
          "dateRange": "11~",
          "ikoma": "RR",
          "": "",
          "kyb": 348029,
          "__1": "PCL-421",
          "__2": ""
        },
        {
          "brand": "NISSAN",
          "model": "SENTRA",
          "series": "B16",
          "dateRange": "07~12",
          "ikoma": "FR",
          "": "",
          "kyb": 333604,
          "__1": "Inquiry",
          "__2": 333605
        },
        {
          "brand": "NISSAN",
          "model": "SENTRA",
          "series": "B16",
          "dateRange": "07~12",
          "ikoma": "RR",
          "": "",
          "kyb": 341659,
          "__1": "Inquiry",
          "__2": ""
        },
        {
          "brand": "NISSAN",
          "model": "SYLPHY",
          "series": "B17/C12",
          "dateRange": "13~",
          "ikoma": "FR",
          "": "",
          "kyb": 339327,
          "__1": "PCL-254",
          "__2": 339328
        },
        {
          "brand": "NISSAN",
          "model": "SYLPHY",
          "series": "B17/C12",
          "dateRange": "13~",
          "ikoma": "RR",
          "": "",
          "kyb": 349212,
          "__1": "PCL-255",
          "__2": ""
        },
        {
          "brand": "NISSAN",
          "model": "TEANA",
          "series": "J31",
          "dateRange": "03~09",
          "ikoma": "FR",
          "": "",
          "kyb": 334403,
          "__1": "PCL-090",
          "__2": 334404
        },
        {
          "brand": "NISSAN",
          "model": "TEANA",
          "series": "J31",
          "dateRange": "03~09",
          "ikoma": "RR",
          "": "",
          "kyb": 344444,
          "__1": "PCL-091",
          "__2": ""
        },
        {
          "brand": "NISSAN",
          "model": "TEANA",
          "series": "J32",
          "dateRange": "09~",
          "ikoma": "FR",
          "": "",
          "kyb": 339228,
          "__1": "PCL-098",
          "__2": 339229
        },
        {
          "brand": "NISSAN",
          "model": "TEANA",
          "series": "J32",
          "dateRange": "09~",
          "ikoma": "RR",
          "": "",
          "kyb": 348024,
          "__1": "PCL-099",
          "__2": ""
        },
        {
          "brand": "NISSAN",
          "model": "TERRANO/PATHFINDER/QX4",
          "series": "WNYD21",
          "dateRange": "87/10~93",
          "ikoma": "FR",
          "": "PCI-082",
          "kyb": 344200,
          "__1": "",
          "__2": ""
        },
        {
          "brand": "NISSAN",
          "model": "TERRANO/PATHFINDER/QX4",
          "series": "WNYD21",
          "dateRange": "87/10~93",
          "ikoma": "RR",
          "": "PCI-083",
          "kyb": 343245,
          "__1": "",
          "__2": ""
        },
        {
          "brand": "NISSAN",
          "model": "TERRANO/PATHFINDER/QX4",
          "series": "LR50,PR50",
          "dateRange": "95/09~99/01",
          "ikoma": "FR",
          "": "",
          "kyb": 335015,
          "__1": "PCL-106",
          "__2": 335016
        },
        {
          "brand": "NISSAN",
          "model": "TERRANO/PATHFINDER/QX4",
          "series": "LR50,PR50",
          "dateRange": "95/09~99/01",
          "ikoma": "RR",
          "": "PCI-084",
          "kyb": 343388,
          "__1": "",
          "__2": ""
        },
        {
          "brand": "NISSAN",
          "model": "TERRANO/PATHFINDER/QX4",
          "series": "R50 FOR EU",
          "dateRange": "99/02~",
          "ikoma": "FR",
          "": "",
          "kyb": 335030,
          "__1": "PCL-478",
          "__2": 335031
        },
        {
          "brand": "NISSAN",
          "model": "TERRANO/PATHFINDER/QX4",
          "series": "R50 FOR EU",
          "dateRange": "99/02~",
          "ikoma": "RR",
          "": "PCI-159",
          "kyb": "",
          "__1": "",
          "__2": ""
        },
        {
          "brand": "NISSAN",
          "model": "TIIDA/VERSA",
          "series": "C11;SC11",
          "dateRange": "05/04~",
          "ikoma": "FR",
          "": "",
          "kyb": 333390,
          "__1": "PCL-482",
          "__2": 333391
        },
        {
          "brand": "NISSAN",
          "model": "TIIDA/VERSA",
          "series": "C11;SC11",
          "dateRange": "05/04~",
          "ikoma": "RR",
          "": "PCI-174",
          "kyb": 343465,
          "__1": "PCL-483",
          "__2": 343407
        },
        {
          "brand": "NISSAN",
          "model": "TIIDA/VERSA",
          "series": "C11 for CHINA",
          "dateRange": "05/04~",
          "ikoma": "FR",
          "": "",
          "kyb": 333429,
          "__1": "PCL-470",
          "__2": 333430
        },
        {
          "brand": "NISSAN",
          "model": "TIIDA/VERSA",
          "series": "C11 for CHINA",
          "dateRange": "05/04~",
          "ikoma": "RR",
          "": "PCL-477",
          "kyb": 343466,
          "__1": "",
          "__2": ""
        },
        {
          "brand": "NISSAN",
          "model": "TITAN",
          "series": "A60",
          "dateRange": "04~15",
          "ikoma": "FR",
          "": "Inquiry",
          "kyb": 341600,
          "__1": "",
          "__2": ""
        },
        {
          "brand": "NISSAN",
          "model": "TITAN",
          "series": "A60",
          "dateRange": "04~15",
          "ikoma": "RR",
          "": "Inquiry",
          "kyb": 345067,
          "__1": "",
          "__2": ""
        },
        {
          "brand": "NISSAN",
          "model": "VERSA / VERSA NOTE",
          "series": "N17",
          "dateRange": "11~",
          "ikoma": "FR",
          "": "",
          "kyb": 332152,
          "__1": "PCL-402",
          "__2": 332153
        },
        {
          "brand": "NISSAN",
          "model": "VERSA / VERSA NOTE",
          "series": "N17",
          "dateRange": "11~",
          "ikoma": "RR",
          "": "",
          "kyb": 348029,
          "__1": "PCL-403",
          "__2": ""
        },
        {
          "brand": "NISSAN",
          "model": "X-TRAIL",
          "series": "T30",
          "dateRange": "01~07",
          "ikoma": "FR",
          "": "",
          "kyb": 334360,
          "__1": "PCL-082",
          "__2": 334361
        },
        {
          "brand": "NISSAN",
          "model": "X-TRAIL",
          "series": "T30",
          "dateRange": "01~07",
          "ikoma": "RR",
          "": "",
          "kyb": 334362,
          "__1": "PCL-083",
          "__2": 334363
        },
        {
          "brand": "NISSAN",
          "model": "X-TRAIL",
          "series": "T31",
          "dateRange": "07~",
          "ikoma": "FR",
          "": "",
          "kyb": 339198,
          "__1": "PCL-498*",
          "__2": 339199
        },
        {
          "brand": "NISSAN",
          "model": "X-TRAIL",
          "series": "T31",
          "dateRange": "07~",
          "ikoma": "RR",
          "": "",
          "kyb": 334362,
          "__1": "PCL-199*",
          "__2": 334363
        },
        {
          "brand": "NISSAN",
          "model": "XTERRA",
          "series": "D22",
          "dateRange": "99~",
          "ikoma": "FR",
          "": "Inquiry",
          "kyb": "",
          "__1": "",
          "__2": ""
        },
        {
          "brand": "NISSAN",
          "model": "XTERRA",
          "series": "D22",
          "dateRange": "99~",
          "ikoma": "RR",
          "": "Inquiry",
          "kyb": "",
          "__1": "",
          "__2": ""
        },
        {
          "brand": "NISSAN",
          "model": "XTERRA",
          "series": "D22",
          "dateRange": "05~15",
          "ikoma": "FR",
          "": "PCI-001",
          "kyb": 341468,
          "__1": "",
          "__2": ""
        },
        {
          "brand": "NISSAN",
          "model": "XTERRA",
          "series": "N50",
          "dateRange": "05~15",
          "ikoma": "RR",
          "": "PCI-002",
          "kyb": 345068,
          "__1": "",
          "__2": ""
        },
        {
          "brand": "NISSAN",
          "model": "CABALL",
          "series": "C240",
          "dateRange": "66~",
          "ikoma": "FR",
          "": "PCI-183",
          "kyb": 344325,
          "__1": "",
          "__2": ""
        },
        {
          "brand": "NISSAN",
          "model": "CABALL/CLIPPER/BUS/TRUCK",
          "series": "C340;T65/T40;RM90;CM90",
          "dateRange": "71/10~",
          "ikoma": "FR",
          "": "PCI-184",
          "kyb": 344331,
          "__1": "",
          "__2": ""
        }
];

export default Nissan;